[package]
name = "full-steam-ahead"
version = "1.4.0"
description = "A desktop app to import games from other launchers into Steam."
authors = ["Creeperkatze"]
license = "AGPL-3.0-only"
homepage = "https://full-steam-ahead.creeperkatze.dev"
repository = "https://github.com/creeperkatze/full-steam-ahead"
edition = "2021"

[lib]
name = "full_steam_ahead_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
disable-auto-updates = []

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
crc32fast = "1.5.0"
dirs = "7"
encoding_rs = "0.8.41"
keyvalues-serde = "0.2"
reqwest = { version = "0.13", default-features = false, features = [
    "blocking",
    "json",
    "rustls",
] }
roxmltree = "0.21.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shlex = "2"
sqlite = "0.37"
tauri = { version = "2.0.0", features = ["protocol-asset", "macos-private-api"] }
tauri-plugin-dialog = "2.0.0"
tauri-plugin-opener = "2"
tauri-plugin-process = "2"
tauri-plugin-single-instance = "2.0.0"
tauri-plugin-updater = "2"
thiserror = "2"
tracing = "0.1"
tracing-appender = "0.2"
tracing-error = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
walkdir = "2"

[lints.clippy]
bool_to_int_with_if = "warn"
cloned_instead_of_copied = "warn"
dbg_macro = "warn"
explicit_iter_loop = "warn"
filter_map_next = "warn"
flat_map_option = "warn"
manual_assert = "warn"
manual_let_else = "warn"
match_bool = "warn"
needless_collect = "warn"
redundant_clone = "warn"
redundant_type_annotations = "warn"
todo = "warn"
too_many_arguments = "allow"
uninlined_format_args = "warn"
unnested_or_patterns = "warn"

[target.'cfg(windows)'.dependencies]
bson = "3.1.0"
uuid = "1"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_ToolHelp",
] }
winreg = "0.56"
zerocopy = { version = "0.8", features = ["derive"] }
