// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	detectSteam: () => __TAURI_INVOKE<SteamInstallation>("detect_steam"),
	validateSteamLocation: (path: string) => __TAURI_INVOKE<boolean>("validate_steam_location", { path }),
	grantSteamFlatpakPermission: () => __TAURI_INVOKE<null>("grant_steam_flatpak_permission"),
	readShortcutsForUser: (userSteamId: string) => __TAURI_INVOKE<ShortcutEntry[]>("read_shortcuts_for_user", { userSteamId }),
	scanSources: (request: ScanRequest) => __TAURI_INVOKE<ImportCandidate[]>("scan_sources", { request }),
	createManualCandidate: (request: ManualImportRequest) => __TAURI_INVOKE<ImportCandidate>("create_manual_candidate", { request }),
	createPreviewPlan: (userSteamId: string, candidates: ImportCandidate[], options: Settings) => __TAURI_INVOKE<PreviewPlan>("create_preview_plan", { userSteamId, candidates, options }),
	applyPlan: (request: ApplyRequest) => __TAURI_INVOKE<ApplyResult>("apply_plan", { request }),
	loadSettings: () => __TAURI_INVOKE<Settings>("load_settings"),
	saveSettings: (settings: Settings) => __TAURI_INVOKE<null>("save_settings", { settings }),
	exportSettings: (path: string, settings: Settings) => __TAURI_INVOKE<null>("export_settings", { path, settings }),
	importSettings: (path: string) => __TAURI_INVOKE<Settings>("import_settings", { path }),
	resetSettings: () => __TAURI_INVOKE<Settings>("reset_settings"),
	availableSources: () => __TAURI_INVOKE<ImportSource[]>("available_sources"),
	steamgriddbSearch: (apiKey: string, query: string) => __TAURI_INVOKE<SteamGridDbGame[]>("steamgriddb_search", { apiKey, query }),
	steamgriddbImages: (apiKey: string, gameId: number, kind: ArtworkKind, allowNsfw: boolean) => __TAURI_INVOKE<SteamGridDbImage[]>("steamgriddb_images", { apiKey, gameId, kind, allowNsfw }),
	closeApp: () => __TAURI_INVOKE<void>("close_app"),
	showMainWindow: () => __TAURI_INVOKE<void>("show_main_window"),
	listBackups: () => __TAURI_INVOKE<BackupInfo[]>("list_backups"),
	restoreBackup: (backupId: string) => __TAURI_INVOKE<number>("restore_backup", { backupId }),
	deleteBackup: (backupId: string) => __TAURI_INVOKE<null>("delete_backup", { backupId }),
	deleteAllBackups: () => __TAURI_INVOKE<null>("delete_all_backups"),
	getDebugInfo: () => __TAURI_INVOKE<DebugInfo>("get_debug_info"),
	openLogsFolder: () => __TAURI_INVOKE<null>("open_logs_folder"),
};

/** Events */
export const events = {
	applyProgressEvent: makeEvent<ApplyProgressEvent>("apply-progress-event"),
	scanProgressEvent: makeEvent<ScanProgressEvent>("scan-progress-event"),
};

/* Types */
export type ApplyProgressEvent = {
	step: ApplyStep,
	current: number,
	total: number,
};

export type ApplyRequest = {
	plan: PreviewPlan,
	candidates: ImportCandidate[],
	options: Settings,
};

export type ApplyResult = {
	appliedChanges: PlannedChange[],
	backupsCreated: string[],
};

export type ApplyStep = { kind: "stoppingSteam" } | { kind: "creatingBackups" } | { kind: "applyingArtwork"; gameName: string | null } | { kind: "updatingShortcuts" } | { kind: "updatingCollections" } | { kind: "restartingSteam" };

export type ArtworkAsset = {
	kind: ArtworkKind,
	pathOrUrl: string,
	source: ArtworkSource,
	willReplaceExisting: boolean,
};

export type ArtworkKind = "header" | "capsule" | "hero" | "logo" | "icon";

export type ArtworkMode = "preserveExisting" | "officialSteamPreferred" | "steamGridDbFallback" | "localOverride";

export type ArtworkPlan = {
	mode: ArtworkMode,
	existing: ArtworkAsset[],
	proposed: ArtworkAsset[],
};

export type ArtworkSource = "existingCustom" | "officialSteam" | "steamGridDb" | "localFile" | "missing";

export type BackupInfo = {
	id: string,
	createdAt: string,
	fileCount: number,
	sizeBytes: number,
};

export type BackupPlan = {
	source: string,
	destination: string,
};

export type ChangeKind = "addShortcut" | "updateShortcut" | "writeArtwork" | "updateCollections";

export type CommandError = {
	message: string,
};

export type DebugInfo = {
	appVersion: string,
	os: string,
	arch: string,
	dataPath: string,
};

export type DefaultArtworkSource = "none" | "steam" | "steamGridDb";

export type ImportCandidate = {
	id: string,
	source: ImportSource,
	name: string,
	originalName: string,
	executablePath: string,
	startDir: string,
	launchOptions: string | null,
	existingAppId: number | null,
	matchedSteamAppId: number | null,
	tags: string[],
	artwork: ArtworkPlan,
	urlScheme: string | null,
	launcherPath: string | null,
	useLauncherUrl: boolean,
	needsProton: boolean,
};

export type ImportSource = "manual" | "playnite" | "epic" | "gog" | "amazon" | "bottles" | "flatpak" | "xbox" | "heroic" | "itch" | "legendary" | "lutris" | "miniGalaxy" | "eaApp" | "ubisoftConnect" | { other: string };

/**  Whether games start through their launcher or from their own executable. */
export type LauncherMode = "always" | "whenRequired" | "whenNoExecutable";

export type ManualImportRequest = {
	userSteamId: string,
	executablePath: string,
	displayName: string | null,
	source: ImportSource,
	tags: string[],
};

export type PlannedChange = {
	id: string,
	candidateId: string,
	gameName: string,
	file: string,
	kind: ChangeKind,
	destructive: boolean,
	artworkSource: ArtworkSource | null,
	artworkKind: ArtworkKind | null,
	collectionName: string | null,
};

export type PreviewPlan = {
	userSteamId: string,
	changes: PlannedChange[],
	filesToChange: string[],
	backups: BackupPlan[],
	requiresSteamRestart: boolean,
};

export type ScanProgressEvent = {
	source: ImportSource,
	status: ScanStatus,
	found: number,
};

export type ScanRequest = {
	userSteamId: string,
	includeSources: ImportSource[],
};

export type ScanStatus = "scanning" | "done";

export type Settings = {
	stopSteam: boolean,
	restartSteam: boolean,
	createCollections: boolean,
	addSelfShortcut: boolean,
	steamLocation: string | null,
	sources: { [key in string]: SourceSettings },
	steamGridDb: SteamGridDbSettings,
	defaultArtworkSource: DefaultArtworkSource,
	launcherMode: LauncherMode,
	locale: string | null,
	colorScheme: string | null,
	updateNotifications: boolean,
};

export type ShortcutEntry = {
	appId: number,
	appName: string,
	exe: string,
	startDir: string,
	icon: string,
	shortcutPath: string,
	launchOptions: string,
	isHidden: boolean,
	allowDesktopConfig: boolean,
	allowOverlay: boolean,
	openVr: boolean,
	devkit: boolean,
	devkitGameId: string,
	lastPlayTime: number,
	tags: string[],
};

export type SourceSettings = {
	enabled: boolean,
	customPath: string | null,
};

export type SteamGridDbGame = {
	id: number,
	name: string,
};

export type SteamGridDbImage = {
	id: number,
	url: string,
	thumbnailUrl: string,
	width: number,
	height: number,
};

export type SteamGridDbSettings = {
	enabled: boolean,
	apiKey: string | null,
	allowNsfw: boolean,
};

export type SteamInstallation = {
	installPath: string,
	users: SteamUser[],
	running: boolean,
	/**  Sandboxed Steam is missing the permission `flatpak-spawn --host` needs to launch shortcuts. */
	needsFlatpakPermission: boolean,
};

export type SteamUser = {
	steamId: string,
	accountName: string | null,
	avatarPath: string | null,
	shortcutsPath: string,
	gridPath: string,
	collectionsPath: string,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

