name: Crowdin (pull)

on:
  schedule:
    - cron: '0 7 * * MON'
  workflow_dispatch:

concurrency:
  group: i18n-management

jobs:
  pull_translations:
    name: Pull translations from Crowdin
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: i18n-pull:${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.ref }}

      - name: Download translations from Crowdin
        uses: crowdin/github-action@9af557de76d70c480f88065d336f445a362f402b # v3.1.0
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          push_translations: true
          localization_branch_name: sync/translations
          commit_message: 'chore: sync translations from Crowdin'
          create_pull_request: true
          pull_request_title: 'chore: sync translations from Crowdin'
          pull_request_body: |
            Automated by [`i18n-pull.yml`](${{ github.server_url }}/${{ github.repository }}/blob/${{ github.ref_name }}/.github/workflows/i18n-pull.yml).

            - 🌐 [Contribute to translations on Crowdin](https://crowdin.com/project/full-steam-ahead)
            - 🔄 [Re-run the workflow to update this PR](${{ github.server_url }}/${{ github.repository }}/actions/workflows/i18n-pull.yml)
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
