name: Publish to Winget

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag to publish"
        required: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - uses: vedantmgoyal9/winget-releaser@a8fff44b123f115ce4c21543edf8b677376fc7e0 # main
        with:
          identifier: Creeperkatze.FullSteamAhead
          installers-regex: '-setup\.exe$'
          release-tag: ${{ inputs.tag || github.event.release.tag_name }}
          token: ${{ secrets.WINGET_TOKEN }}
